version: '3'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: LabLubyProva02
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - pg
    build: .
    command: node ace serve --watch
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
